name: enhanced_containers_foundation
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  uuid: ^4.5.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
